workspace:
  base: /src
  path: github.com/GetTerminus/blog

pipeline:
  commit-check:
    image: monachus/hugo
    environment:
      - master
    commands:
      - uname -a
      - rm -rf public && mkdir public
      - git worktree prune
      - rm -rf .git/worktrees/public/
      - git worktree add -B gh-pages public upstream/gh-pages
      - rm -rf public/*
      - hugo
      - cd public && git add --all && git commit -m "Publishing to gh-pages" && cd .. && git push upstream gh-pages

    when:
      branch: master
