workspace:
  base: /src
  path: github.com/GetTerminus/blog

pipeline:
  commit-check:
    image: monachus/hugo
    commands:
      - hugo
  publish-gh-pages:
    image: monachus/hugo
    commands: 
      - rm -rf public && mkdir public
      - git worktree prune
      - git worktree add -B gh-pages public origin/gh-pages
      - rm -rf public/*
      - hugo
      - cd public && git add --all
      - git commit -m "Publishing to gh-pages" && git push origin gh-pages
    when:
      event: push
      branch: master
