workspace:
  base: /src
  path: github.com/GetTerminus/blog

pipeline:
  commit-check:
    image: monachus/hugo
    commands:
      - hugo
  publish-gh-pages:
    image: monachus/hugo
    commands:
      - bash publish_to_ghpages.sh 
    when:
      branch: master
