workspace:
  base: /src
  path: github.com/GetTerminus/blog

pipeline:
  commit-check:
    image: monachus/hugo
    environment:
      - master
    commands:
      - rm -rf public
      - git worktree add -B gh-pages public upstream/gh-pages
      - hugo
      - cd public && git add --all && git commit -m "Publishing to gh-pages" && cd ..
      - git push upstream gh-pages
    when:
      branch: master