workspace:
  base: /src
  path: github.com/GetTerminus/blog

pipeline:
  commit-check:
    image: monachus/hugo
    environment:
      - master
    commands:
      - hugo
      - cd public && git add --all && git commit -m "Publishing to gh-pages" && cd ..
      - git push origin gh-pages
    when:
      branch: master