workspace:
  base: /src
  path: github.com/GetTerminus/blog

pipeline:
  commit-check:
    image: monachus/hugo
    environment:
      - master
    commands:
      - bash publish_to_ghpages.sh
    when:
      branch: master
