name: test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    container:
      image: monachus/hugo
    steps:
      - name: Pull
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/src/github.com/${{ github.repository }}

      - name: Publish GH Pages
        working-directory: ${{ github.workspace }}/src/github.com/${{ github.repository }}
        run: |
          bash /__w/blog/blog/src/github.com/GetTerminus/blog/publish_to_ghpages.sh
