name: test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: monachus/hugo
    steps:
      - name: Pull
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/src/github.com/${{ github.repository }}

      - name: Publish GH Pages
        #if: github.ref == 'refs/heads/master'
        working-directory: ${{ github.workspace }}/src/github.com/${{ github.repository }}
        run: |
          pwd
          ls -la
          publish_to_ghpages.sh
