name: test

on: push

jobs:
  gh-pages:
    runs-on: [self-hosted, standard]
    steps:
      - name: Pull
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.GH_ACTIONS_SSH_PRIVATE_KEY }}

      - name: Publish GH Pages
        #if: github.ref == 'refs/heads/master'
        uses: docker://monachus/hugo
        with:
          args: bash -c "publish_to_ghpages.sh;"
